### ISSUE TITLE
Add documentation in the editor

### ISSUE THREAD

**Issue by DearFox** [Daylily-Zeleen/Godot-DragonBones#11]
![изображение](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/59219907/c5a2b1d7-6739-498c-bb06-2625cd8dbbfe)

**Comment by Daylily-Zeleen** [comment]
@DearFox please describe the detail of your problem.

**Comment by JekSun97** [comment]
> @DearFox please describe the detail of your problem.

This is what I wrote about earlier, the documentation is severely lacking, there are many functions, and not all functions are clear

**Comment by Daylily-Zeleen** [comment]
> This is what I wrote about earlier, the documentation is severely lacking, there are many functions, and not all functions are clear

I‘m not sure this issue is duplicate or not.
Accroding to @DearFox 's image, it seems that the EditorHelp can't work correctly.
The lack of documentation dose not equal to make the EditorHelp broken.

So I need more detail about what happen in this issue.

-------------------------------------------------------------------------------
By the way, due to the limitation of GDExtension, we can't add description to EditorHelp currently.

**Comment by JekSun97** [comment]
@DearFox Try to describe the action taken to create the problem, perhaps this is an error of the godot himself, and it is worth reporting there

**Comment by DearFox** [comment]
There are simply no descriptions of some classes. 
 Click on one of this plugin's classes (in the code editor in godot) using ctrl and it will open this blank window.
 I'm using v4.2.2.stable.official [15073afe3]

**Comment by Daylily-Zeleen** [comment]
Which classes? How to reproduce?

**Comment by DearFox** [comment]
oh ok, guess I had to reboot godot and now everything works.
 Of course there is no description of the functions, but I can look them up.
 
 Then I think it would be more correct to rename this issues to “please add a description for methods and functions to the documentation inside godot”

**Comment by Daylily-Zeleen** [comment]
> Then I think it would be more correct to rename this issues to “please add a description for methods and functions to the documentation inside godot”

Please refer to this [comment](https://github.com/Daylily-Zeleen/Godot-DragonBones/issues/11#issuecomment-2058765748).

**Comment by DearFox** [comment]
> Which classes? How to reproduce?

I meant this documentation.  And it seems I just needed to restart the project with the plugin, and everything worked (not sure why I had problems before.)
![изображение](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/59219907/9c44c33a-80f8-4f23-b766-614c07929a73)

**Comment by Daylily-Zeleen** [comment]
> I meant this documentation. And it seems I just needed to restart the project with the plugin, and everything worked (not sure why I had problems before.)


This is due to godot limitation, every GDExtension plugin should be loaded at least once and restart editor to make classes  visiable in EditorHelp.
