### ISSUE TITLE
New format .dbfactory

### ISSUE THREAD

**Issue by JekSun97** [Daylily-Zeleen/Godot-DragonBones#12]
I wanted to update the version, but I didn’t see anything new except the new format (.dbfactory), can you tell me more about it, what is it for, when exactly does it appear, and why not JSON?

**Comment by Daylily-Zeleen** [comment]
Please refer to [Readme](https://github.com/Daylily-Zeleen/Godot-DragonBones#contents) or [Release Note](https://github.com/Daylily-Zeleen/Godot-DragonBones/releases/tag/v0.2.0).

**Comment by JekSun97** [comment]
> Please refer to [Readme](https://github.com/Daylily-Zeleen/Godot-DragonBones#contents) or [Release Note](https://github.com/Daylily-Zeleen/Godot-DragonBones/releases/tag/v0.2.0).

I read this and that, but I still didn’t understand the meaning of this format. =\

**Comment by JekSun97** [comment]
all I understood is that if there is a json file, it will create a dbfactory file next to it, but why and for what purpose is still not clear.

**Comment by Daylily-Zeleen** [comment]
This plugin is not import `.json` anymore, a resource file with extension `.dbfactory` will be generated if there have `xxx_ske.json/dbbin` and `xxx_tex.json`.

You should delete `.import` files of `.json` now.

The reasom of this change is that `.json` is not resource file by default, and may be neglected when exporting, generate a new resource file to solve this problem.
In order to recognize the `DragonBonesFactory` resource file more easier, I use a new format `dbfactory` instead of `res/tres`.
That's all.

**Comment by JekSun97** [comment]
> This plugin is not import `.json` anymore, a resource file with extension `.dbfactory` will be generated if there have `xxx_ske.json/dbbin` and `xxx_tex.json`.
> 
> You should delete `.import` files of `.json` now.
> 
> The reasom of this change is that `.json` is not resource file by default, and may be neglected when exporting, generate a new resource file to solve this problem. In order to recognize the `DragonBonesFactory` resource file more easier, I use a new format `dbfactory` instead of `res/tres`. That's all.

That is, after each creation of the dbfactory file, the parent json file can be deleted?

**Comment by Daylily-Zeleen** [comment]
> That is, after each creation of the dbfactory file, the parent json file can be deleted?

No，they should be keeped for VCS and exporting.

`dbfactory` just hold paths of DragonBones file (.json/.dbbin), and these files will be copy to `.godot` folder for exporting.

To get rid of `.json` after exporting, `DragonBonesFactory` will search the true path (.json/.dbbin) first, if not exists, it will find the files in `.godot`.

Please refer source code for more details. 

> You should delete `.import` files of `.json` now.

Just delete the `.import` file which are generated by importing `.json` by the old version.
