### ISSUE TITLE
Configuration issue on the Asset Library

### ISSUE THREAD

**Issue by akien-mga** [Daylily-Zeleen/Godot-DragonBones#13]
Hi,

I just tried installing this in a Godot project, but there's a configuration clash as this addon provides a `project.godot`, which can't be installed alongside the pre-existing project's `project.godot`.

You might want to split it into two addons, one with only the extension to add to an existing project, and one as a "Demo" with the demo + the extension configured, to install from the Project Manager as a standalone project.

**Comment by Daylily-Zeleen** [comment]
Thanks for your reminder.
Now I added `export-ignore` to ".gitattribute" and submit the latest commit hash to Asset Library.
