### ISSUE TITLE
Dragon Bones not showing up in Project Settings/Plugins

### ISSUE THREAD

**Issue by Lykdraft** [Daylily-Zeleen/Godot-DragonBones#14]
Dragonbones doesn't show up in Project/Project Settings/Plugins on:
- GD 4.2 OSX 
- GD 4.2 Windows
- GD 4.3 beta 1 OSX, 
- GD 4.3 beta 1 Win.

Doesn't show up with the downloaded addon .  Doesn't show up with the pre-compiled gdextendion version.
Seems to me like it doesn't work at all.

Best,
tL.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by Daylily-Zeleen** [comment]
@Lykdraft A GDExtension plugin not need to be enabled in ProjectSettings.
If it work, you can see related classes, such as `DragonBones`, in EditorHelp (popup by pressing "F1").

-----------
By the way, I have not mac device to do test, so I can't guarantee that this plugin can work properly on macos.

**Comment by Daylily-Zeleen** [comment]
@simulified I don't know what do you mean. If it is not related this issue, please open a new issue and add more detail about what you encountered and how to reproduce. Otherwise, I don't think anyone can help you solve the problem.

**Comment by Lykdraft** [comment]
Ah, I see. Thank you for your explanation!
Indeed, I made today a new project on Windows and I could add a Dragonbones Node (from you) into the project, somehow I didn't see this before. Not sure why. But it is what it is... :)

I will double-check tomorrow on Mac, but I am pretty sure that it didn't show up. Nonetheless, I will close this now, consider this solved. (I will report on the mac in the next few days.) Thanks again! Best, tL.

**Comment by Lykdraft** [comment]
Okay, so on windows, when I add a `dragon_ske.dbfactory` into the Dragonbones Factory slot, I can't see the Image. I also get an error in the debugger window:
```
E 0:00:01:0115   GDExtension::_register_extension_class_internal: Attempt to register extension class 'GDMesh', which appears to be already registered.
  <C++ Error>    Condition "ClassDB::class_exists(class_name)" is true.
  <C++ Source>   core\extension\gdextension.cpp:386 @ GDExtension::_register_extension_class_internal()
```
Not sure if this is a GDextension bug or if this is on your side... or if this has anything to do with your gdextension at all..?

**Comment by Daylily-Zeleen** [comment]
Please open a new issue and provide more details about how to reproduce.
I can't reproduce this bug by just drag a `.dbfactory` to set.
