### ISSUE TITLE
DragonBones gdextension doesn't show the image when dragon_ske.dbfactory is draggen into the factory-slot

### ISSUE THREAD

**Issue by Lykdraft** [Daylily-Zeleen/Godot-DragonBones#15]
Okay, so on Windows (Godot 4.2 Stable) when I add a `dragon_ske.dbfactory ` into the 
Dragonbones Factory slot, I can't see the Image.  I also get an error in the debugger window:
```
E 0:00:01:0115   GDExtension::_register_extension_class_internal: Attempt to register extension class 'GDMesh', which appears to be already registered.
  <C++ Error>    Condition "ClassDB::class_exists(class_name)" is true.
  <C++ Source>   core\extension\gdextension.cpp:386 @ GDExtension::_register_extension_class_internal()
```
Not sure if this is a GDextension bug or if this is on your side... or if this has anything to do with your gdextension at all..?

Thing is, this happens also when I use the "Welcome Page/Armature Demo" Dragon. 

_(Exported as DragonBones JSON, DataVersion 4.5,5.0,5.5, Image Type: Texture Atlas.
FYI: When I use the same files with the "other" dragonbones plugin, which actually shouldn't work in 4.x, 
it shows the image, (but I can't get the animation to work). Here, with your GDextension it doesn't show the image at all.)_

**Comment by Daylily-Zeleen** [comment]
I think, maybe, you already use other DragonBones plugin (or your Godot engine compile with other DragonBoens module), or arleady has the `GDMesh` class. In other words, there have conflict between plugins.

You should create a new project with official Godot Engine to begin your test.

**Comment by Lykdraft** [comment]
Ah, ok, will do that. Reporting back in a couple of minutes...

**Comment by Lykdraft** [comment]
Yeah, that's it, you're right. I used a Godot source build which had the other dragonBones code compiled into the engine. 
Sorry 'bout that... :)

**Comment by Lykdraft** [comment]
Just double-checked the exact same procedure now on Mac OSX 10.14.6 ( with a normal Godot 4.3 beta 1
already build from their site) with a fresh new project.

After the download and install from the assetstore **no DragonBones node shows up.**
In the windows version, the Node shows up. Just to let you know. ;)
