### ISSUE TITLE
crash on macos

### ISSUE THREAD

**Issue by wwqdrh** [Daylily-Zeleen/Godot-DragonBones#17]
hello, i got a crash on macos

below is crash stack

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80ddf014a __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80de28ebd pthread_kill + 262
2   libsystem_c.dylib             	    0x7ff80dd4ea79 abort + 126
3   Godot                         	       0x10b372bdc 0x10ab39000 + 8625116
4   libsystem_platform.dylib      	    0x7ff80de57fdd _sigtramp + 29
5   ???                           	               0x0 ???
6   Godot                         	       0x10b917432 0x10ab39000 + 14541874
7   libdragonbones.macos.template_debug.dylib	       0x117b54988 godot::Node* godot::internal::_call_native_mb_ret_obj<godot::Node>(void const*, void*) + 25 (engine_ptrcall.hpp:50) [inlined]
8   libdragonbones.macos.template_debug.dylib	       0x117b54988 godot::Node::get_parent() const + 88 (node.cpp:142)
9   libdragonbones.macos.template_debug.dylib	       0x117a70c62 godot::DragonBonesArmature::dispose(bool) + 194
10  libdragonbones.macos.template_debug.dylib	       0x117a66718 godot::DragonBonesArmature::~DragonBonesArmature() + 40
11  libdragonbones.macos.template_debug.dylib	       0x117a99157 godot::DragonBonesArmature::free(void*, void*) + 23
12  Godot                         	       0x10ee8a091 0x10ab39000 + 70586513
13  Godot                         	       0x10d08da23 0x10ab39000 + 39143971
14  Godot                         	       0x10ee78cf7 0x10ab39000 + 70515959
15  Godot                         	       0x10d08da13 0x10ab39000 + 39143955
16  Godot                         	       0x10ee78cf7 0x10ab39000 + 70515959
17  Godot                         	       0x10d08da13 0x10ab39000 + 39143955
18  Godot                         	       0x10ee78cf7 0x10ab39000 + 70515959
19  Godot                         	       0x10d0c9d05 0x10ab39000 + 39390469
20  Godot                         	       0x10b36f163 0x10ab39000 + 8610147
21  Godot                         	       0x10b3a2168 0x10ab39000 + 8819048
22  dyld                          	    0x7ff80da9d366 start + 1942

**Comment by Daylily-Zeleen** [comment]
Please provide steps of how to reproduce.
I add debug symbol for debug build in ci. please use the [new binaries (after the compile finished)](https://github.com/Daylily-Zeleen/Godot-DragonBones/actions/runs/9680555983) to test again for getting detail infomations.

**Comment by wwqdrh** [comment]
sorry, my mistake, the new version no this crash, thanks your work
