### ISSUE TITLE
Editor crashes when resize `texture_atlas_json_file_list` of `DragonBoneFactory`.

### ISSUE THREAD

**Issue by JekSun97** [Daylily-Zeleen/Godot-DragonBones#19]
If we select DragonBones from the demo, go to the Factory section, click on the `texture_atlas_json_file_list` array, then click on the field with the resource path, for example where `res://assets/Bicycle_tex.json`, then click on the button with the folder or try to increase the amount of the array, the editor closes

https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/a8f8ee2c-592b-47f7-8e7a-344306a5572d

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

**Comment by Daylily-Zeleen** [comment]
I can't reproduce with following your steps. Please provide MRP.

I notice that your `DragonBones` node has not icon, it seems that you are still using the old version.
Please update the plugin and try again.

**Comment by JekSun97** [comment]
@Daylily-Zeleen  Indeed, this error does not exist in the latest version

**Comment by JekSun97** [comment]
No, I was still able to reproduce this problem in the new version.

1. Open the dbfactory resource.
2: In the inspector, click the texture_atlas_json_file_list array, then on the path input field, click any other button, for example array size

**Comment by Daylily-Zeleen** [comment]
Fix by [this commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/3994a408ab7ae500eb83e901a4e307f9178518ba).
