### ISSUE TITLE
Cannot use another character

### ISSUE THREAD

**Issue by JekSun97** [Daylily-Zeleen/Godot-DragonBones#20]
I created two different characters/skeletons, one is a standard ubbie, the other is a modified one, and I can't use it using the plugin.

![1](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/a2808d41-46a5-4e72-9cd0-60e098b11d87)
![2](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/73bbac15-324b-47fd-b347-4a75fb4823ee)
![3](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/5ae7a61b-9d7e-48a4-a395-82f838a981da)

I'll attach this file for testing, you can open it in Dragon Bones using the import menu:
[ubbynew.zip](https://github.com/user-attachments/files/16118476/ubbynew.zip)

**Comment by JekSun97** [comment]
When I use this dbfactory I get this error:
![err](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/ccaa32ed-e46c-499e-bf0c-7bacfef336ad)

```
 src\dragonbones_factory.cpp:380 - Parameter "dragon_bones_data" is null.
  src\dragonbones.cpp:146 - Condition "!p_armature->is_initialized()" is true.
```

**Comment by Daylily-Zeleen** [comment]
Support changing armature by this [commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/92ef4967c053c5787a13a7956f32dae74961c50f).

Avoid print error message by this [commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/ee41bd98452432bc0758d78da06cc49ac3975422).
