### ISSUE TITLE
If there is only one animation, it does not play

### ISSUE THREAD

**Issue by JekSun97** [Daylily-Zeleen/Godot-DragonBones#24]
If a model has one animation and we switch in the editor from [none] to this animation, it does not play, this can be checked on a model with the "new" skin from this issue - #20 .

I also found another small problem: when we replace a dbfactory with another dbfactory, the "Dragon Bones Data Name" and "Armature Name" are not updated until we switch their value to something else.
This error always appears when changing dbfactory:
![22](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/077b2da5-1c4e-4c84-a4d2-083effe26099)

**Comment by Daylily-Zeleen** [comment]
> If a model has one animation and we switch in the editor from [none] to this animation, it does not play, this can be checked on a model with the "new" skin from this issue - #20 .

I think this can be fix by this [commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/167a3d4195dd31a440abaf0a96471e2d85a16d13), please try it.

----------------------------
> I also found another small problem: when we replace a dbfactory with another dbfactory, the "Dragon Bones Data Name" and "Armature Name" are not updated until we switch their value to something else.

I know this issue, but I think this is expected. If change dbfactory is a unexpected operation, recorver to the previous dbfactory will not lost the previous settings. And if these settings can't be found from the new dbfactory, it will try to fallback to the first object (for example, the first DragonBonesData which can be found in the list).

-----------------------------


> This error always appears when changing dbfactory:
> ![22](https://private-user-images.githubusercontent.com/130399274/346528912-077b2da5-1c4e-4c84-a4d2-083effe26099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzU3NzYsIm5iZiI6MTcyMDQzNTQ3NiwicGF0aCI6Ii8xMzAzOTkyNzQvMzQ2NTI4OTEyLTA3N2IyZGE1LTFjNGUtNGM4NC1hNGQyLTA4M2VmZmUyNjA5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMDQ0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGQ2N2JmZDYzOTkzYjhlNGY3ZGYwMGNmMmIwM2U2ZTVmZmIwZTlkZmIyYWI2MWE3NjY2NTVjMmY3MzE1ZmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JwFRGOW05CP4s16Yx7SN107YYmKqC0gGKID2vSPpT7A)

Fix by this new [commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/368f63aa055f7121526040b4a83c52ffb0d4eb22).

**Comment by JekSun97** [comment]
@Daylily-Zeleen  I have never met such programmers who fix errors so quickly, thank you!

**Comment by JekSun97** [comment]
@Daylily-Zeleen  I just built the plugin and tested it, the first problem is not fixed:

https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/943b800f-76f2-4e3f-97fa-04919560b7ca

After selecting [none], the animation still remains animation0, but at the same time it stops, and we cannot play the animation0 animation

**Comment by Daylily-Zeleen** [comment]
> @Daylily-Zeleen I just built the plugin and tested it, the first problem is not fixed:
> 
>  0708.1.mp4 
> After selecting [none], the animation still remains animation0, but at the same time it stops, and we cannot play the animation0 animation

I think this [commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/b491b80020b2b3258f9fb77346f34315a6c34d6c) can fix this bug truly.

**Comment by JekSun97** [comment]
@Daylily-Zeleen  Problem solved, thanks!
