### ISSUE TITLE
[Feature Request]Collision shape follow Bone, similar to Bone attachment

### ISSUE THREAD

**Issue by flashshare** [Daylily-Zeleen/Godot-DragonBones#31]
### Describe the project you are working on

I am testing the beat them up game style. It is much easier if the collision shape can attach or follow the movement of the bone.

### Describe the problem or limitation you are having in your project

It takes too much time to adjust the collision shape according bone  movement

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I found a similar approach but for 3D. 
https://godotengine.org/asset-library/asset/1003

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I am not sure how to achieve this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The plugin https://godotengine.org/asset-library/asset/1003 looks quite short to implement, but not sure

**Comment by Daylily-Zeleen** [comment]
This is not what DragonBones focus on.
You can implement by few lines of script.

For example: 
```
class_name DragonBonesBoneAttachment
extends Mark2D

@export var bone_name: String

func _process() -> void:
    if not get_parent() is DragonBones:
        printerr("DragonBonesBoneAttachment must be a child of DragonBones")
        return

    if not is_instance_valid(get_parent().armature):
        return

    var bone := get_parent().armature.get_bone(bone_name)
    if not is_instance_valid(bone):
        printerr("Invalid bone name: ", bone_name)
        return
    transform = bone.global_transform

```

**Comment by flashshare** [comment]
Thanks.
