### ISSUE TITLE
Building the extension

### ISSUE THREAD

**Issue by JekSun97** [Daylily-Zeleen/Godot-DragonBones#7]
I tried to build the plugin using SCons, but errors are coming out, could you explain where to put godot-cpp and other assembly details, for example commands for a specific platform, and release and debug mode, and I would also be grateful if you wrote a separate one README.md in English, thank you!

**Comment by Daylily-Zeleen** [comment]
The godot-cpp just at the root of this project.
I found it the submodules have not synchronize to this remote repo correctly, now I fixed it, please pull the latest commit and ensure submodules are cloned correctly in your local repo.

The English README.md I will update later.

**Comment by JekSun97** [comment]
> The godot-cpp just at the root of this project. I found it the submodules have not synchronize to this remote repo correctly, now I fixed it, please pull the latest commit and ensure submodules are cloned correctly in your local repo.
> 
> The English README.md I will update later.

thanks, now I see godot-cpp, but what about a command like target=x86_64 and platform=windows, etc?

**Comment by Daylily-Zeleen** [comment]
> thanks, now I see godot-cpp, but what about a command like target=x86_64 and platform=windows, etc?

Please follow the build system of godot-cpp, they are identical.

**Comment by Daylily-Zeleen** [comment]
The English readme already committed.

Please close this issue if solved.
