### ISSUE TITLE
problem with some animations

### ISSUE THREAD

**Issue by JekSun97** [Daylily-Zeleen/Godot-DragonBones#8]
I decided to test the plugin, and encountered a problem that some animations become distorted when the Z index is changed, for example, if you open the official “Ubbie” model and enable the “turn face” animation, the left hand either disappears or goes into the background, which is why it is not visible, in DB 5.6 everything looks good.

I exported the animation in JSON format, version 5.5

Godot 4.2.1:
![3123](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/d8e0f57f-0b12-4621-b3a7-97ba7e141379)

Dragon Bones 5.6:
![332](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/130399274/1303127d-5df0-4e23-af5a-15a3c8d6fa57)

**Comment by Daylily-Zeleen** [comment]
Already fix buy [b5de86d0105470dcbc645e73b6877191bd656070](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/b5de86d0105470dcbc645e73b6877191bd656070).

**Comment by JekSun97** [comment]
> Already fix buy [b5de86d0105470dcbc645e73b6877191bd656070](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/b5de86d0105470dcbc645e73b6877191bd656070).

THANKS!!! <3
