### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by vyshliy** [Daylily-Zeleen/Godot-DragonBones#9]
The plugin looks very useful. However, for some reason I can’t run the plugin downloaded from the assets library or the compiled version from GitHub. Tested on Linux with Godot version 4.2 and 4.3. Usually the log looks something like this:

![Screenshot_2024-04-12_08-46-11](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/72736632/b1b72a4b-96dd-4335-9f76-0e104d689fe0)

**Comment by Daylily-Zeleen** [comment]
Already fix by [this commit](https://github.com/Daylily-Zeleen/Godot-DragonBones/commit/a4690cd21b5ff3edfa76298f55c0f597f0ed26b0).

Please download the latest from [release page](https://github.com/Daylily-Zeleen/Godot-DragonBones/releases).

This is ci issue, so I have not update version code.

**Comment by Daylily-Zeleen** [comment]
@vyshliy Please cloes this issue if your comfirm it is solved

**Comment by vyshliy** [comment]
It looks like the behavior has changed, but the plugin still won't launch. I haven’t worked with GDextensions before, so I want to clarify that in order to run compiled version from Github I need to download the corresponding release (in my case it’s Godot-DragonBones-linux-template_release-x86_64-v0.1.1) and just put the gddragonbones folder in the addons folder in my project?

Now the error looks like this. The correct path to the project is marked in blue, and the path where the extension was downloaded is marked in red. The red path has nothing to do with the Godot project at all, but nevertheless it is indicated in the log.

![Screenshot_2024-04-12_11-48-48](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/72736632/411ad256-babf-4768-8e2d-9a506b3488a6)

**Comment by Daylily-Zeleen** [comment]
@vyshliy It seems that godot find the shared library outside project.
But we can't reproduce this problem.

Please try to modify the "gddragonbones.gdextension" file, change relative path to absolute path:
From:
```
linux.x86_64.debug = "bin/libgddragonbones.linux.template_debug.x86_64.so"
linux.x86_64.release = "bin/libgddragonbones.linux.template_release.x86_64.so"
linux.x86_32.debug = "bin/libgddragonbones.linux.template_debug.x86_32.so"
linux.x86_32.release = "bin/libgddragonbones.linux.template_release.x86_32.so"
```
To:
```
linux.x86_64.debug = "res://addons/gddragonbones/bin/libgddragonbones.linux.template_debug.x86_64.so"
linux.x86_64.release = "res://addons/gddragonbones/bin/libgddragonbones.linux.template_release.x86_64.so"
linux.x86_32.debug = "res://addons/gddragonbones/bin/libgddragonbones.linux.template_debug.x86_32.so"
linux.x86_32.release = "res://addons/gddragonbones/bin/libgddragonbones.linux.template_release.x86_32.so"
```

And plaese report me that this change can fix your problem or not.

**Comment by vyshliy** [comment]
It was my mistake - the bin folder was missing the debug version, so relative paths are fine. I think there will be no confusion when the entire extension can be downloaded from the asset library.
Now everything works perfectly fine and the issue is no longer relevant.

Thank you very much for the work you have done.
